# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.7
_src_path: https://github.com/jupyterlab/extension-template
author_email: amihaio@gmail.com
author_name: jupyterlab_scratchpad
data_format: string
file_extension: ''
has_binder: true
has_settings: true
kind: frontend
labextension_name: jupyterlab_scratchpad
mimetype: ''
mimetype_name: ''
project_short_description: JupyterLab extension for a side panel with a scratchpad
python_name: jupyterlab_scratchpad
repository: https://github.com/amihaiOff/jupyterlab_scratchpad
test: true
viewer_name: ''

